# Starter pipeline



# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: TerraformTaskV2@2
  inputs:
    provider: 'aws'
    command: 'init'
    workingDirectory: './NEW EKS'
    backendServiceAWS: 'terra'
    backendAWSBucketName: 'azurepipeline966'
    backendAWSKey: 'terraform/terrafor.tfstate'
    
- task: TerraformTaskV2@2
  inputs:
    provider: 'aws'
    command: 'plan'
    workingDirectory: './NEW EKS'
    commandOptions: '-out=tfplan'
    environmentServiceNameAWS: 'terra'

- task: TerraformTaskV2@2
  inputs:
    provider: 'aws'
    command: 'apply'
    workingDirectory: './NEW EKS'
    commandOptions: '-auto-approve'
    environmentServiceNameAWS: 'terra'

- task: TerraformTaskV2@2
  inputs:
    provider: 'aws'
    command: 'apply'
    workingDirectory: './NEW EKS'
    commandOptions: '-destroy'
    environmentServiceNameAWS: 'terra'